{% set name = "types-urllib3" %}
{% set version = "1.26.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-urllib3-{{ version }}.tar.gz
  sha256: bb0959ca2bb55eb0bacba08a0d504c5925347ec8bf8c6b2a754be5fcf3945cae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for urllib3
  license: Apache-2.0
  # License need to be packaged from upstream
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
